name: Generate Animation

# Run automatically every 12 hours
schedule:
  - cron: "0 */12 * * *"  # Executes every 12 hours

# Allow manual triggering of the workflow
workflow_dispatch:

# Trigger on every push to the master branch
push:
  branches:
    - master

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Generate the GitHub contribution grid snake SVG
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      # Push the generated SVG to the 'output' branch
      - name: Push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
